## Resumen de la revisión 1 <a class="tocSkip"></a>

<b>Comentario de Reviewer</b> <a class="tocSkip"></a>

Felicitaciones Kata, tu trabajo está muy bien realizado. Destaco el orden que tiene el notebook y la correcta aplicación de los conceptos solicitados. Hay un par de errores pequeños pero que debes poner atención y corregir antes de aprobar finalmente el notebook, estoy seguro que serán rápidos de realizar. Dejé también algunas sugerencias para hacer mejor el notebook (en amarillo), que no son obligatorias.

Saludos
</div>

## Resumen de la revisión 2 <a class="tocSkip"></a>

# Análisis del riesgo de incumplimiento de los prestatarios

Tu proyecto consiste en preparar un informe para la división de préstamos de un banco. Deberás averiguar si el estado civil y el número de hijos de un cliente tienen un impacto en el incumplimiento de pago de un préstamo. El banco ya tiene algunos datos sobre la solvencia crediticia de los clientes.

Tu informe se tendrá en cuenta al crear una **puntuación de crédito** para un cliente potencial. La **puntuación de crédito** se utiliza para evaluar la capacidad de un prestatario potencial para pagar su préstamo.


Hipotesis 1: Los clientes casados y con hijos tienden a cumplir con el pago de un préstamo.
Hipotesis 2: Los clientes divorciados o solteros con mas de un hijo podrian incumplir con el pago de un préstamo.
Hipotesis 3: Los clientes solteros sin hijos podrian o no incumplir con el pago de un prestamo dependiento de su nivel educativo.

## Abre el archivo de datos y mira la información general. 

In [1]:
# Cargar todas las librerías
import pandas
import pandas as pd

In [2]:
# Carga los datos
credit_scoring = pd.read_csv('credit_scoring_eng.csv')

## Ejercicio 1. Exploración de datos

**Descripción de los datos**
- `children` - el número de hijos en la familia
- `days_employed` - experiencia laboral en días
- `dob_years` - la edad del cliente en años
- `education` - la educación del cliente
- `education_id` - identificador de educación
- `family_status` - estado civil
- `family_status_id` - identificador de estado civil
- `gender` - género del cliente
- `income_type` - tipo de empleo
- `debt` - ¿había alguna deuda en el pago de un préstamo?
- `total_income` - ingreso mensual
- `purpose` - el propósito de obtener un préstamo


In [3]:
# Vamos a ver cuántas filas y columnas tiene nuestro conjunto de datos
credit_scoring.shape


(21525, 12)

In [4]:
# vamos a mostrar las primeras 25 filas
credit_scoring.head(25)

children  days_employed  dob_years            education  education_id  \
0          1   -8437.673028         42    bachelor's degree             0   
1          1   -4024.803754         36  secondary education             1   
2          0   -5623.422610         33  Secondary Education             1   
3          3   -4124.747207         32  secondary education             1   
4          0  340266.072047         53  secondary education             1   
5          0    -926.185831         27    bachelor's degree             0   
6          0   -2879.202052         43    bachelor's degree             0   
7          0    -152.779569         50  SECONDARY EDUCATION             1   
8          2   -6929.865299         35    BACHELOR'S DEGREE             0   
9          0   -2188.756445         41  secondary education             1   
10         2   -4171.483647         36    bachelor's degree             0   
11         0    -792.701887         40  secondary education             1   
12         0            NaN         65  secondary education             1   
13         0   -1846.641941         54         some college             2   
14         0   -1844.956182         56    bachelor's degree             0   
15         1    -972.364419         26  secondary education             1   
16         0   -1719.934226         35  secondary education             1   
17         0   -2369.999720         33    bachelor's degree             0   
18         0  400281.136913         53  secondary education             1   
19         0  -10038.818549         48  SECONDARY EDUCATION             1   
20         1   -1311.604166         36  secondary education             1   
21         1    -253.685166         33  secondary education             1   
22         1   -1766.644138         24  secondary education             1   
23         0    -272.981385         21    bachelor's degree             0   
24         1  338551.952911         57  secondary education             1   

        family_status  family_status_id gender income_type  debt  \
0             married                 0      F    employee     0   
1             married                 0      F    employee     0   
2             married                 0      M    employee     0   
3             married                 0      M    employee     0   
4   civil partnership                 1      F     retiree     0   
5   civil partnership                 1      M    business     0   
6             married                 0      F    business     0   
7             married                 0      M    employee     0   
8   civil partnership                 1      F    employee     0   
9             married                 0      M    employee     0   
10            married                 0      M    business     0   
11            married                 0      F    employee     0   
12  civil partnership                 1      M     retiree     0   
13            married                 0      F    employee     0   
14  civil partnership                 1      F    business     1   
15            married                 0      F    employee     0   
16            married                 0      F    employee     0   
17  civil partnership                 1      M    employee     0   
18    widow / widower                 2      F     retiree     0   
19           divorced                 3      F    employee     0   
20            married                 0      M    employee     0   
21  civil partnership                 1      F    employee     0   
22  civil partnership                 1      F    employee     0   
23  civil partnership                 1      M    employee     0   
24          unmarried                 4      F     retiree     0   

    total_income                                   purpose  
0      40620.102                     purchase of the house  
1      17932.802                              car purchase  
2      23341.752                     purchase of 

A primera vista se observan varios datos negativos en los dias que ha trabajado el cliente, es necesario averiguar a que se debe. Es dificil saber si corresponde a los días trabajados y solo hay que hacerlo un numero positivo o tal vez esta relacionado al tipo de empleo. Es necesario analizar mas a fondo ese dato para decidir como manejar esos datos.

In [5]:
# Obtener información sobre los datos
credit_scoring.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      19351 non-null  float64
 11  purpose           21525 non-null  object 
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


Tenemos valores ausentes en las columnas de days_employed y total_income. Ademas, tenemos días trabajados que superan los 20.000 días o los 55 años que es lo máximo posible suponiendo que alguien trabajo desde los 15 años hasta los 70. 

In [6]:
# Veamos la tabla filtrada con valores ausentes de la columna de tiempo trabajado o days_employed

credit_scoring.dropna(subset = ['days_employed'])

children  days_employed  dob_years            education  education_id  \
0             1   -8437.673028         42    bachelor's degree             0   
1             1   -4024.803754         36  secondary education             1   
2             0   -5623.422610         33  Secondary Education             1   
3             3   -4124.747207         32  secondary education             1   
4             0  340266.072047         53  secondary education             1   
...         ...            ...        ...                  ...           ...   
21520         1   -4529.316663         43  secondary education             1   
21521         0  343937.404131         67  secondary education             1   
21522         1   -2113.346888         38  secondary education             1   
21523         3   -3112.481705         38  secondary education             1   
21524         2   -1984.507589         40  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
0                married                 0      F    employee     0   
1                married                 0      F    employee     0   
2                married                 0      M    employee     0   
3                married                 0      M    employee     0   
4      civil partnership                 1      F     retiree     0   
...                  ...               ...    ...         ...   ...   
21520  civil partnership                 1      F    business     0   
21521            married                 0      F     retiree     0   
21522  civil partnership                 1      M    employee     1   
21523            married                 0      M    employee     1   
21524            married                 0      F    employee     0   

       total_income                  purpose  
0         40620.102    purchase of the house  
1         17932.802             car purchase  
2         23341.752    purchase of the house  
3         42820.568  supplementary education  
4         25378.572        to have a wedding  
...             ...                      ...  
21520     35966.698     housing transactions  
21521     24959.969        purchase of a car  
21522     14347.610                 property  
21523     39054.888        buying my own car  
21524     13127.587             to buy a car  

[19351 rows x 12 columns]

Al eliminar los valores ausentes unicamente en la columna de days_employed se observa que el numero de filas corresponde al numero de filas no nulas (19.351)en dicha columna y en total_income.
Eliminare los datos ausentes en el DataFrame para las dos columnas para comprobar si los valores ausentes en las dos columnas son en las mismas filas.

In [7]:
# Apliquemos múltiples condiciones para filtrar datos y veamos el número de filas en la tabla filtrada.
print(f'Valores ausentes en cada columna de datos:')
credit_scoring.isnull().sum()

Valores ausentes en cada columna de datos:


children               0
days_employed       2174
dob_years              0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64

In [8]:
# Tabla con datos ausentes en las columnas de antigüedad laboral e ingresos totales:
credit_scoring_null = credit_scoring[credit_scoring['days_employed'].isnull()&credit_scoring['total_income'].isnull()]
credit_scoring_null 

children  days_employed  dob_years            education  education_id  \
12            0            NaN         65  secondary education             1   
26            0            NaN         41  secondary education             1   
29            0            NaN         63  secondary education             1   
41            0            NaN         50  secondary education             1   
55            0            NaN         54  secondary education             1   
...         ...            ...        ...                  ...           ...   
21489         2            NaN         47  Secondary Education             1   
21495         1            NaN         50  secondary education             1   
21497         0            NaN         48    BACHELOR'S DEGREE             0   
21502         1            NaN         42  secondary education             1   
21510         2            NaN         28  secondary education             1   

           family_status  family_status_id gender    income_type  debt  \
12     civil partnership                 1      M        retiree     0   
26               married                 0      M  civil servant     0   
29             unmarried                 4      F        retiree     0   
41               married                 0      F  civil servant     0   
55     civil partnership                 1      F        retiree     1   
...                  ...               ...    ...            ...   ...   
21489            married                 0      M       business     0   
21495  civil partnership                 1      F       employee     0   
21497            married                 0      F       business     0   
21502            married                 0      F       employee     0   
21510            married                 0      F       employee     0   

       total_income                   purpose  
12              NaN         to have a wedding  
26              NaN                 education  
29              NaN    building a real estate  
41              NaN  second-hand car purchase  
55              NaN         to have a wedding  
...             ...                       ...  
21489           NaN         purchase of a car  
21495           NaN          wedding ceremony  
21497           NaN       building a property  
21502           NaN    building a real estate  
21510           NaN              car purchase  

[2174 rows x 12 columns]

In [9]:
# Tabla filtrada sin valores ausentes para calcular el porcentaje de valores ausentes
credit_scoring_filtered = credit_scoring.dropna()   
# Calculando el porcentaje de valores ausentes:
print(f'Tenemos un {((len(credit_scoring)-len(credit_scoring_filtered))/len(credit_scoring)*100):.2f}% de datos ausentes')

Tenemos un 10.10% de datos ausentes


**Conclusión intermedia**

Despues de eliminar los valores ausentes por separado y en conjunto de las columnas de days_employed y total_income, se puede concluir que los valores ausentes en ambas columnas son de la misma fila. 

Hay un 10,10% de valores ausentes en el conjunto de datos. Aún es muy precipitado decidir si eliminamos las filas con valores ausentes o si podemos completarlos sin afectar los resultados del análisis.

Primero voy a analizar las filas que no tienen datos de días trabajados e ingresos totales usando las columnas de datos que estan completas para ver si hay una similitud en ese grupo de clientes. Tal vez este analisis me de una idea de la razón por la que faltan estos valores. 

**Vamos a investigar a los clientes que no tienen datos sobre ingresos mensuales y tiempo trabajado usando los datos de las columnas que están completas**

In [10]:
# Según el tipo de ingreso:
print(f'conjunto de datos con filas con datos ausentes:')
print((credit_scoring_null['income_type'].value_counts()*100)/(len(credit_scoring_null)))
print('_________________________________________________')
print()
print(f'conjunto de datos cocompleto:')
(credit_scoring['income_type'].value_counts()*100)/len(credit_scoring)

conjunto de datos con filas con datos ausentes:
employee         50.827967
business         23.367065
retiree          18.997240
civil servant     6.761730
entrepreneur      0.045998
Name: income_type, dtype: float64
_________________________________________________

conjunto de datos cocompleto:


employee                       51.656214
business                       23.623693
retiree                        17.914053
civil servant                   6.778165
unemployed                      0.009292
entrepreneur                    0.009292
student                         0.004646
paternity / maternity leave     0.004646
Name: income_type, dtype: float64

In [11]:
# Según el nivel de educación:
print(credit_scoring_null['education'].value_counts())
print('_________________________________________________')
print()
print(f'conjunto de datos con filas con datos ausentes:')
print((credit_scoring_null['education'].str.lower().value_counts()*100)/len(credit_scoring_null)) # Unificando los datos a minusculas para gestionar duplicados
print('_________________________________________________')
print()
print(f'conjunto de datos completo:')
(credit_scoring['education'].str.lower().value_counts()*100)/len(credit_scoring)

secondary education    1408
bachelor's degree       496
SECONDARY EDUCATION      67
Secondary Education      65
some college             55
Bachelor's Degree        25
BACHELOR'S DEGREE        23
primary education        19
Some College              7
SOME COLLEGE              7
Primary Education         1
PRIMARY EDUCATION         1
Name: education, dtype: int64
_________________________________________________

conjunto de datos con filas con datos ausentes:
secondary education    70.837167
bachelor's degree      25.022999
some college            3.173873
primary education       0.965961
Name: education, dtype: float64
_________________________________________________

conjunto de datos completo:


secondary education    70.768873
bachelor's degree      24.436702
some college            3.456446
primary education       1.310105
graduate degree         0.027875
Name: education, dtype: float64

In [12]:
# Según el estado civil:
print(f'conjunto de datos con filas con datos ausentes:')
print((credit_scoring_null['family_status'].value_counts()*100)/(len(credit_scoring_null)))
print('_________________________________________________')
print()
print(f'conjunto de datos completo:')
credit_scoring['family_status'].value_counts()*100/len(credit_scoring)

conjunto de datos con filas con datos ausentes:
married              56.899724
civil partnership    20.331187
unmarried            13.247470
divorced              5.151794
widow / widower       4.369825
Name: family_status, dtype: float64
_________________________________________________

conjunto de datos completo:


married              57.514518
civil partnership    19.405343
unmarried            13.068525
divorced              5.551684
widow / widower       4.459930
Name: family_status, dtype: float64

In [13]:
# Según el género:
print(f'conjunto de datos con filas con datos ausentes:')
print(credit_scoring_null['gender'].value_counts()*100/(len(credit_scoring_null)))
print('_________________________________________________')
print()
print(f'conjunto de datos completo:')
credit_scoring['gender'].value_counts()*100/len(credit_scoring)

conjunto de datos con filas con datos ausentes:
F    68.26127
M    31.73873
Name: gender, dtype: float64
_________________________________________________

conjunto de datos completo:


F      66.137050
M      33.858304
XNA     0.004646
Name: gender, dtype: float64

In [14]:
# Clasificación por grupo de edad:

def age_group(age):
    if age <= 0:
        return 'error'     # Identificando cuantos clientes tienen edad cero o negativa
    if 0 < age < 18: 
        return 'children'  # Identificando los clientes menores de edad para solicitar un prestamo
    if age <= 64:
        return 'adult'    # Identificando los clientes con edad laboral
    return 'retired'       # Identificando los clientes con edad para estar pensionados o retirados

print(f'conjunto de datos con filas con datos ausentes:')
print(credit_scoring_null['dob_years'].apply(age_group).value_counts())
print('_________________________________________________')
print()
print(f'conjunto de datos con filas completo:')
credit_scoring['dob_years'].apply(age_group).value_counts()

conjunto de datos con filas con datos ausentes:
adult      2083
retired      81
error        10
Name: dob_years, dtype: int64
_________________________________________________

conjunto de datos con filas completo:


adult      20525
retired      899
error        101
Name: dob_years, dtype: int64

In [15]:
# Según el número de hijos:
print(f'conjunto de datos con filas con datos ausentes:')
print(credit_scoring_null['children'].value_counts()*100/len(credit_scoring_null))
print('_________________________________________________')
print()
print(f'conjunto de datos completo:')
credit_scoring['children'].value_counts()*100/len(credit_scoring)

conjunto de datos con filas con datos ausentes:
 0     66.191352
 1     21.849126
 2      9.383625
 3      1.655934
 20     0.413983
 4      0.321987
-1      0.137994
 5      0.045998
Name: children, dtype: float64
_________________________________________________

conjunto de datos completo:


 0     65.732869
 1     22.383275
 2      9.547038
 3      1.533101
 20     0.353078
-1      0.218351
 4      0.190476
 5      0.041812
Name: children, dtype: float64

In [16]:
# Según si el cliente ha incumplido el pago de un préstamo alguna vez:
print(f'conjunto de datos con filas con datos ausentes:')
print(credit_scoring_null['debt'].value_counts()*100/len(credit_scoring_null))
print('_________________________________________________')
print()
print(f'conjunto de datos completo:')
credit_scoring['debt'].value_counts()*100/len(credit_scoring)

conjunto de datos con filas con datos ausentes:
0    92.180313
1     7.819687
Name: debt, dtype: float64
_________________________________________________

conjunto de datos completo:


0    91.911731
1     8.088269
Name: debt, dtype: float64

In [17]:
# Según el proposito del prestamo:
print(f'conjunto de datos con filas con datos ausentes:')
print((credit_scoring_null['purpose'].value_counts()*100)/(len(credit_scoring_null)))
print('_________________________________________________')
print()
print(f'conjunto de datos completo:')
credit_scoring['purpose'].value_counts()*100/len(credit_scoring)

conjunto de datos con filas con datos ausentes:
having a wedding                            4.231831
to have a wedding                           3.725851
wedding ceremony                            3.495860
construction of own property                3.449862
housing transactions                        3.403864
buy real estate                             3.311868
purchase of the house for my family         3.265869
transactions with my real estate            3.265869
transactions with commercial real estate    3.219871
housing renovation                          3.219871
buy commercial real estate                  3.081877
buying property for renting out             2.989880
property                                    2.851886
real estate transactions                    2.805888
buy residential real estate                 2.805888
housing                                     2.759890
building a property                         2.713891
cars                                        2.62189

wedding ceremony                            3.702671
having a wedding                            3.609756
to have a wedding                           3.595819
real estate transactions                    3.140534
buy commercial real estate                  3.084785
buying property for renting out             3.033682
housing transactions                        3.033682
transactions with commercial real estate    3.024390
purchase of the house                       3.005807
housing                                     3.005807
purchase of the house for my family         2.977933
construction of own property                2.950058
property                                    2.945412
transactions with my real estate            2.926829
building a real estate                      2.908246
buy real estate                             2.898955
building a property                         2.880372
purchase of my own house                    2.880372
housing renovation                          2.

**Posibles razones por las que hay valores ausentes en los datos**

Despues de evaluar varias distribuciones no se observa algún patron entre los clientes de valores ausentes, lo que si se puede comprobar es que la distribucion de clientes es similar entre la tabla de datos completa y la tabla de clientes que tienen datos ausentes en las columnas de ingreso mensual y dias trabajados. 
Al realizar varios filtros de distribucion de los datos que estan completos se observa que el conjunto de datos con valores ausentes es representativo a la distribucion de datos completa.

Comprobare esta hipotesis comparando los dos conjuntos de datos.

In [18]:
# Comprobación de la distribución filtrada
credit_scoring_filtered.describe()

children  days_employed     dob_years  education_id  \
count  19351.000000   19351.000000  19351.000000  19351.000000   
mean       0.537388   63046.497661     43.255336      0.819079   
std        1.371408  140827.311974     12.579170      0.550104   
min       -1.000000  -18388.949901      0.000000      0.000000   
25%        0.000000   -2747.423625     33.000000      1.000000   
50%        0.000000   -1203.369529     42.000000      1.000000   
75%        1.000000    -291.095954     53.000000      1.000000   
max       20.000000  401755.400475     75.000000      4.000000   

       family_status_id          debt   total_income  
count      19351.000000  19351.000000   19351.000000  
mean           0.972249      0.081184   26787.568355  
std            1.420596      0.273125   16475.450632  
min            0.000000      0.000000    3306.762000  
25%            0.000000      0.000000   16488.504500  
50%            0.000000      0.000000   23202.870000  
75%            1.000000      0.000000   32549.611000  
max            4.000000      1.000000  362496.645000

In [19]:
# Comprobando el porcentaje de datos de days_employed son mayores a 55 años trabajados o 20.000 días:
print('Porcentaje de datos mayores a 55 años trabajados:')
print(len(credit_scoring[credit_scoring['days_employed']>20000])/len(credit_scoring)*100)
      
credit_scoring[credit_scoring['days_employed']>20000].sort_values(by='days_employed', ascending=False)


Porcentaje de datos mayores a 55 años trabajados:
16.004645760743323


children  days_employed  dob_years            education  education_id  \
6954          0  401755.400475         56  secondary education             1   
10006         0  401715.811749         69    bachelor's degree             0   
7664          1  401675.093434         61  secondary education             1   
2156          0  401674.466633         60  secondary education             1   
7794          0  401663.850046         61  secondary education             1   
...         ...            ...        ...                  ...           ...   
7229          1  328827.345667         32  secondary education             1   
14783         0  328795.726728         62    bachelor's degree             0   
17782         0  328771.341387         56  secondary education             1   
9328          2  328734.923996         41    bachelor's degree             0   
20444         0  328728.720605         72  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
6954     widow / widower                 2      F     retiree     0   
10006          unmarried                 4      F     retiree     0   
7664             married                 0      F     retiree     0   
2156             married                 0      M     retiree     0   
7794   civil partnership                 1      F     retiree     0   
...                  ...               ...    ...         ...   ...   
7229   civil partnership                 1      F     retiree     0   
14783            married                 0      F     retiree     0   
17782            married                 0      F     retiree     0   
9328             married                 0      M     retiree     0   
20444    widow / widower                 2      F     retiree     0   

       total_income                                   purpose  
6954      28204.551                        housing renovation  
10006      9182.441                      getting an education  
7664      20194.323                      housing transactions  
2156      52063.316                                      cars  
7794       7725.831                          wedding ceremony  
...             ...                                       ...  
7229      19546.075                         to have a wedding  
14783     12790.431                         buying my own car  
17782     10983.688  transactions with commercial real estate  
9328      20319.600          transactions with my real estate  
20444     15443.094       purchase of the house for my family  

[3445 rows x 12 columns]

In [20]:
# Comprobando la distribución en el conjunto de datos entero
credit_scoring.describe()


children  days_employed     dob_years  education_id  \
count  21525.000000   19351.000000  21525.000000  21525.000000   
mean       0.538908   63046.497661     43.293380      0.817236   
std        1.381587  140827.311974     12.574584      0.548138   
min       -1.000000  -18388.949901      0.000000      0.000000   
25%        0.000000   -2747.423625     33.000000      1.000000   
50%        0.000000   -1203.369529     42.000000      1.000000   
75%        1.000000    -291.095954     53.000000      1.000000   
max       20.000000  401755.400475     75.000000      4.000000   

       family_status_id          debt   total_income  
count      21525.000000  21525.000000   19351.000000  
mean           0.972544      0.080883   26787.568355  
std            1.420324      0.272661   16475.450632  
min            0.000000      0.000000    3306.762000  
25%            0.000000      0.000000   16488.504500  
50%            0.000000      0.000000   23202.870000  
75%            1.000000      0.000000   32549.611000  
max            4.000000      1.000000  362496.645000

**Conclusiones**

Al comparar el conjunto de datos filtrado con los datos originales se observan similitudes en la media y los datos de maximo y minimo, además de los porcentajes de distribución.

Despues de comparar entre si la distribucion de datos de cada una de las columnas con las filas de datos ausentes y sin ellos se observa que se corresponden con el 10% de cada distribución, es decir, la cantidad de clientes casados en la tabla con datos ausentes son aproximadamente el 10% de los clientes de la tabla y asi se repite con las otras columnas de forma similar. 

Adicionalmente en la columna de days_employed hay 16% de datos que indican que han trabajado mas de 55 años o incluso mil años lo cuál es poco probable para personas menores de 70 años para el primer caso e imposible para el segundo, asi que esos datos los ajustare con el mismo críterio de los valores ausentes 

No se puede atribuir ningún patrón para explicar los datos ausentes así que son aleatorios. 

Antes de analizar los datos modificare la forma en que se escribieron los datos de grado de estudio y transformare o agrupare los datos del proposito del prestamo ya que el conjunto de datos tiene varias formas para reprentar razones similares para solicitar el prestamo.

## Transformación de datos


In [21]:
# Modificando los valores de la columna de educación para que todos esten en minuscula:
credit_scoring['education'] = credit_scoring['education'].str.lower()
credit_scoring['education'].value_counts()

secondary education    15233
bachelor's degree       5260
some college             744
primary education        282
graduate degree            6
Name: education, dtype: int64

Veemos la columna 'children'

In [22]:
# Veamos la distribución de los valores en la columna `children`
print(credit_scoring['children'].value_counts())
print()
rate_data_negative_ch = len(credit_scoring[credit_scoring['children']<0])/len(credit_scoring['children'])*100
print(f'Tenemos un {rate_data_negative_ch:.2f}% de datos negativos para el numero de hijos.')
print()
rate_data_20_ch = len(credit_scoring[credit_scoring['children']>5])/len(credit_scoring['children'])*100
print(f'Tenemos un {rate_data_20_ch:.2f}% de datos de 20 para el numero de hijos.')


 0     14149
 1      4818
 2      2055
 3       330
 20       76
-1        47
 4        41
 5         9
Name: children, dtype: int64

Tenemos un 0.22% de datos negativos para el numero de hijos.

Tenemos un 0.35% de datos de 20 para el numero de hijos.


Hay 47 datos con la cantidad de hijos en -1 lo que posiblemente fue un error al ingresar el dato como no puedo averiguarlo y dado que solo representan el 0,22% de los datos voy a hacer el dato positivo, es decir, 1 hijo.
Hay 76 datos con 20 hijos lo que podría ser real o tal vez un error pero como no puedo averiguarlo y dado que solo representan el 0,35% de los datos voy a transformar el 20 a 2 hijos.

In [23]:
# Eliminando los datos negativos en la columna 'children'
credit_scoring['children'] = credit_scoring['children'].abs()

In [24]:
# Cambiando el dato de 20 hijos a 2 hijos en la columna 'children'
credit_scoring.loc[(credit_scoring['children']>5), 'children'] = 2

In [25]:
# Comprobar la columna `children` de nuevo para asegurarnos de que todo está arreglado
credit_scoring['children'].value_counts()


0    14149
1     4865
2     2131
3      330
4       41
5        9
Name: children, dtype: int64

Ahora revisemos la columna `days_employed`

In [26]:
# Datos problemáticos en 'days_employed':
rate_data_negative_de = len(credit_scoring[credit_scoring['days_employed']<0])/len(credit_scoring['days_employed'])*100
print(f'Tenemos un {rate_data_negative_de:.2f}% de datos negativos para la antigüedad laboral o días que ha estado trabajando el cliente.')

Tenemos un 73.90% de datos negativos para la antigüedad laboral o días que ha estado trabajando el cliente.


La cantidad de días trabajados no puede ser negativa. Lo mejor sería consultar que pudo suceder con el ingreso de los datos que los volvio negativos, sin embargo, no es posible y no puedo perder mas del 70% de la información.

La mejor decisión es tomar esto como un error técnico que volvio los valores negativos y los convertire en positivos.

Tambien sera necesario pasarlos a números enteros ya que no se puede trabajar 0.2 días, pero esto lo realizare más adelante cuando me haya hecho cargo de los valores ausentes de la columna.

In [27]:
# Cambiando los datos negativos a positivos:
credit_scoring['days_employed'] = credit_scoring['days_employed'].abs()


In [28]:
# Comprobando el resultado:
credit_scoring[credit_scoring['days_employed']<0]

Empty DataFrame
Columns: [children, days_employed, dob_years, education, education_id, family_status, family_status_id, gender, income_type, debt, total_income, purpose]
Index: []

Ahora revisemos la columna `dob:years`. 

In [29]:
# Revisando 'dob_years'para calcular el porcentaje de valores con edad cero y tal vez menores de 18 años:
print(credit_scoring['dob_years'].apply(age_group).value_counts())
rate_data_negative_dy=len(credit_scoring[credit_scoring['dob_years']<18])/len(credit_scoring['dob_years'])*100
print(f'Tenemos un {rate_data_negative_dy:.2f}% de datos con edad cero.')

adult      20525
retired      899
error        101
Name: dob_years, dtype: int64
Tenemos un 0.47% de datos con edad cero.


Dentro del conjunto de datos hay clientes  con edades en cero que tienen estudios de secundaria o más altos lo que significa que el dato no fue ingresado. 

Debido a que esto representa solo el 0,47% de los datos podría reemplazarlos por la media para no perder esa información. 

In [30]:
def replace_cero_dob_years(credit_scoring):
    medians_age = credit_scoring.groupby('children').dob_years.median()
    
    credit_scoring.loc[(credit_scoring["dob_years"]==0), "dob_years"] = medians_age.loc[0] # Reemplaza edad para cero hijos
    credit_scoring.loc[(credit_scoring["dob_years"]==0), "dob_years"] = medians_age.loc[1] # Reemplaza edad para un hijo
    credit_scoring.loc[(credit_scoring["dob_years"]==0), "dob_years"] = medians_age.loc[2] # Reemplaza edad para 2 hijos
    credit_scoring.loc[(credit_scoring["dob_years"]==0), "dob_years"] = medians_age.loc[3] # Reemplaza edad para 3 hijos
    credit_scoring.loc[(credit_scoring["dob_years"]==0), "dob_years"] = medians_age.loc[4] # Reemplaza edad para 4 hijos
    credit_scoring.loc[(credit_scoring["dob_years"]==0), "dob_years"] = medians_age.loc[5] # Reemplaza edad para 5 hijos
    return credit_scoring

# Aplicando la funcion:
credit_scoring = replace_cero_dob_years(credit_scoring)

# Probando que los datos fueron reemplazados:
credit_scoring

children  days_employed  dob_years            education  education_id  \
0             1    8437.673028         42    bachelor's degree             0   
1             1    4024.803754         36  secondary education             1   
2             0    5623.422610         33  secondary education             1   
3             3    4124.747207         32  secondary education             1   
4             0  340266.072047         53  secondary education             1   
...         ...            ...        ...                  ...           ...   
21520         1    4529.316663         43  secondary education             1   
21521         0  343937.404131         67  secondary education             1   
21522         1    2113.346888         38  secondary education             1   
21523         3    3112.481705         38  secondary education             1   
21524         2    1984.507589         40  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
0                married                 0      F    employee     0   
1                married                 0      F    employee     0   
2                married                 0      M    employee     0   
3                married                 0      M    employee     0   
4      civil partnership                 1      F     retiree     0   
...                  ...               ...    ...         ...   ...   
21520  civil partnership                 1      F    business     0   
21521            married                 0      F     retiree     0   
21522  civil partnership                 1      M    employee     1   
21523            married                 0      M    employee     1   
21524            married                 0      F    employee     0   

       total_income                  purpose  
0         40620.102    purchase of the house  
1         17932.802             car purchase  
2         23341.752    purchase of the house  
3         42820.568  supplementary education  
4         25378.572        to have a wedding  
...             ...                      ...  
21520     35966.698     housing transactions  
21521     24959.969        purchase of a car  
21522     14347.610                 property  
21523     39054.888        buying my own car  
21524     13127.587             to buy a car  

[21525 rows x 12 columns]

In [31]:
# Comprobando que ya no quedan datos con edades menor a 18 o valor cero:
credit_scoring[credit_scoring['dob_years']<18]

Empty DataFrame
Columns: [children, days_employed, dob_years, education, education_id, family_status, family_status_id, gender, income_type, debt, total_income, purpose]
Index: []

Ahora revisemos la columna `family_status`. 

In [32]:
# Veamos la columna family_status:
credit_scoring['family_status'].value_counts() # No hay problemas con los datos

married              12380
civil partnership     4177
unmarried             2813
divorced              1195
widow / widower        960
Name: family_status, dtype: int64

Ahora revisemos la columna `gender`

In [33]:
# Veamos la columna gender:
credit_scoring['gender'].value_counts()  

F      14236
M       7288
XNA        1
Name: gender, dtype: int64

In [34]:
# Veamos la fila con valor XNA:
credit_scoring[credit_scoring['gender']=='XNA']  


children  days_employed  dob_years     education  education_id  \
10701         0    2358.600502         24  some college             2   

           family_status  family_status_id gender income_type  debt  \
10701  civil partnership                 1    XNA    business     0   

       total_income          purpose  
10701     32624.825  buy real estate

En la columna de género tengo solo un dato que no esta asignado al genero de mujeres o hombres, esta como 'XNA', debido a que desconozco a que se debe este dato, solo es uno del total y los otros valores de la fila podrían corresponder a un hombre o una mujer lo asignare de forma arbitraría a las mujeres.

In [35]:
#Como solo es un dato lo voy a agregar de manera arbitraria a las mujeres
credit_scoring.loc[credit_scoring['gender']=='XNA', 'gender'] = 'F'

In [36]:
# Comprobando el resultado:
credit_scoring['gender'].value_counts()

F    14237
M     7288
Name: gender, dtype: int64

Ahora vamos a revisar la columna `income_type`. 

In [37]:
# Veamos la columna income_type:
credit_scoring['income_type'].value_counts()   #No hay datos problema

employee                       11119
business                        5085
retiree                         3856
civil servant                   1459
unemployed                         2
entrepreneur                       2
student                            1
paternity / maternity leave        1
Name: income_type, dtype: int64

In [38]:
#Revisando la tabla ajustada
credit_scoring.describe()

children  days_employed     dob_years  education_id  \
count  21525.000000   19351.000000  21525.000000  21525.000000   
mean       0.479721   66914.728907     43.518606      0.817236   
std        0.755528  139030.880527     12.222040      0.548138   
min        0.000000      24.141633     19.000000      0.000000   
25%        0.000000     927.009265     34.000000      1.000000   
50%        0.000000    2194.220567     43.000000      1.000000   
75%        1.000000    5537.882441     53.000000      1.000000   
max        5.000000  401755.400475     75.000000      4.000000   

       family_status_id          debt   total_income  
count      21525.000000  21525.000000   19351.000000  
mean           0.972544      0.080883   26787.568355  
std            1.420324      0.272661   16475.450632  
min            0.000000      0.000000    3306.762000  
25%            0.000000      0.000000   16488.504500  
50%            0.000000      0.000000   23202.870000  
75%            1.000000      0.000000   32549.611000  
max            4.000000      1.000000  362496.645000

Tenemos un conjunto de datos sin valores negativos en la antigüedad laboral (días trabajando) y en el numero de hijos. Reemplace el 0.43% de los datos de edad y cambie de negativo a positivo más del 70% de los datos de días trabajados porque posiblemente el valor negativo se debio a un problema técnico.

# Trabajar con valores ausentes

Para reemplazar los valores ausentes con la media o mediana de las columnas de days_employed y total_income que representan el 10% del conjunto de datos decidí usar el diccionario agg() para calcular estos valores agrupando los clientes según **la edad y el nivel educativo** para el caso de los ingresos mensuales y por el **edad y genero** para el caso de días trabajados. 

### Restaurar valores ausentes en `total_income`

Resolvi analizar y elegír las medias o medianas según el grupo al que pertenece el cliente ya que hay mucha diferencia entre el ingreso maximo y minimo de los clientes y estas variables son las que requiero para trabajar mi hipotesis.

Primero voy a dividirlos por grupo de **edad** y calcular la media y la mediana, despues analizare los mismos valores estadisticos al agrupar los clientes por **nivel educativo**.

In [39]:
# Función para calcular la categoría de edad por decadas:
def age_group_dec(row):
    age=row['dob_years']
    
    if 18 <= age <= 30: 
        return '18-30'  
    if 30 < age <= 40:
        return '31-40'
    if 40 < age <= 50:
        return '41-50'
    if 50 < age <= 60:
        return '51-60'
    if 60 < age <= 70:
        return '61-70' 
    return '+70'      

In [40]:
# Crear una nueva columna basada en la función
credit_scoring['age_group_dec'] = credit_scoring.apply(age_group_dec, axis=1)

In [41]:
# Probando si la función funciona bien
print(credit_scoring.loc[39, ['dob_years', 'age_group_dec']])
print()
print(credit_scoring.loc[0, ['dob_years', 'age_group_dec']])
print()
print(credit_scoring.loc[4, ['dob_years', 'age_group_dec']])
print()
credit_scoring.loc[21521, ['dob_years', 'age_group_dec']]


dob_years           31
age_group_dec    31-40
Name: 39, dtype: object

dob_years           42
age_group_dec    41-50
Name: 0, dtype: object

dob_years           53
age_group_dec    51-60
Name: 4, dtype: object



dob_years           67
age_group_dec    61-70
Name: 21521, dtype: object

In [42]:
# Comprobando cómo se ven los valores en la nueva columna
credit_scoring.sort_values(by='dob_years', ascending=True)

children  days_employed  dob_years            education  education_id  \
766           0     796.983636         19         some college             2   
8316          0     556.088508         19  secondary education             1   
4098          0     111.762790         19  secondary education             1   
9218          0     322.024011         19  secondary education             1   
10235         0     793.358581         19  secondary education             1   
...         ...            ...        ...                  ...           ...   
3460          0  344623.836105         74  secondary education             1   
2557          0  372861.103965         74  secondary education             1   
11532         0    6682.867814         74  secondary education             1   
19642         0  380150.387046         74  secondary education             1   
8880          0    1678.969771         75  secondary education             1   

           family_status  family_status_id gender    income_type  debt  \
766              married                 0      F       employee     0   
8316           unmarried                 4      F       employee     0   
4098   civil partnership                 1      M       business     0   
9218   civil partnership                 1      F       business     0   
10235            married                 0      F       employee     0   
...                  ...               ...    ...            ...   ...   
3460             married                 0      M        retiree     0   
2557             married                 0      F        retiree     0   
11532  civil partnership                 1      F       employee     0   
19642    widow / widower                 2      F        retiree     0   
8880     widow / widower                 2      F  civil servant     0   

       total_income                           purpose age_group_dec  
766       12929.944   buying property for renting out         18-30  
8316      10963.857              university education         18-30  
4098      14700.281                  having a wedding         18-30  
9218      16588.237                 to have a wedding         18-30  
10235     21009.404                housing renovation         18-30  
...             ...                               ...           ...  
3460       8760.759  transactions with my real estate           +70  
2557       6868.368                              cars           +70  
11532     15831.345                 to have a wedding           +70  
19642      7214.327                      car purchase           +70  
8880      24525.224                to become educated           +70  

[21525 rows x 13 columns]

Para decicidir que valor usar para reemplazar los valores ausentes en la columna de ingresos mensuales agrupare los clientes por variables que normalmente afectan los ingresos de las personas como la **edad y el nivel educativo**.

Calculare la media, la mediana, el maximo y el minimo de ingresos mensuales para cada grupo de clientes y según las similitudes observadas elegire un valor medio o mediana para reemplazar en la columna de total_income.

Creare la tabla 'credit_scoring_filtered' que solo tenga datos sin valores ausentes. Estos datos se utilizarán para restaurar los valores ausentes

In [43]:
credit_scoring_filtered = credit_scoring.dropna()   #Tabla sin las filas de valores ausente
credit_scoring_filtered

children  days_employed  dob_years            education  education_id  \
0             1    8437.673028         42    bachelor's degree             0   
1             1    4024.803754         36  secondary education             1   
2             0    5623.422610         33  secondary education             1   
3             3    4124.747207         32  secondary education             1   
4             0  340266.072047         53  secondary education             1   
...         ...            ...        ...                  ...           ...   
21520         1    4529.316663         43  secondary education             1   
21521         0  343937.404131         67  secondary education             1   
21522         1    2113.346888         38  secondary education             1   
21523         3    3112.481705         38  secondary education             1   
21524         2    1984.507589         40  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
0                married                 0      F    employee     0   
1                married                 0      F    employee     0   
2                married                 0      M    employee     0   
3                married                 0      M    employee     0   
4      civil partnership                 1      F     retiree     0   
...                  ...               ...    ...         ...   ...   
21520  civil partnership                 1      F    business     0   
21521            married                 0      F     retiree     0   
21522  civil partnership                 1      M    employee     1   
21523            married                 0      M    employee     1   
21524            married                 0      F    employee     0   

       total_income                  purpose age_group_dec  
0         40620.102    purchase of the house         41-50  
1         17932.802             car purchase         31-40  
2         23341.752    purchase of the house         31-40  
3         42820.568  supplementary education         31-40  
4         25378.572        to have a wedding         51-60  
...             ...                      ...           ...  
21520     35966.698     housing transactions         41-50  
21521     24959.969        purchase of a car         61-70  
21522     14347.610                 property         31-40  
21523     39054.888        buying my own car         31-40  
21524     13127.587             to buy a car         31-40  

[19351 rows x 13 columns]

In [44]:
# Comparando la media, la mediana, el máximo y el mínimo del ingreso mensual según grupo de edad:
total_income_grouped_age = credit_scoring_filtered.groupby('age_group_dec').agg(
{'total_income': ['mean', 'median', 'max', 'min', 'count']}
)
total_income_grouped_age

total_income                                        
                       mean      median         max       min count
age_group_dec                                                      
+70            19575.454327  18611.5935   42271.437  3595.641    98
18-30          25817.674826  22957.1850  159522.288  4494.861  3366
31-40          28376.735148  24825.1865  352136.354  3392.845  5170
41-50          28332.806009  24563.6500  362496.645  4036.463  4845
51-60          25482.856294  22056.7710  180613.801  3306.762  4053
61-70          23245.390243  19705.8550  274402.943  3471.216  1819

In [45]:
# Comparando la media. la mediana, el maximo y el minimo del ingreso mensual según el nivel educativo:
total_income_grouped_ed = credit_scoring_filtered.groupby('education').agg(
{'total_income': ['mean', 'median', 'max', 'min', 'count']}
)
total_income_grouped_ed

total_income                                          
                             mean      median         max        min  count
education                                                                  
bachelor's degree    33142.802434  28054.5310  362496.645   5148.514   4716
graduate degree      27960.024667  25161.5835   42945.794  15800.399      6
primary education    21144.882211  18741.9760   78410.774   4049.374    261
secondary education  24594.503037  21836.5830  276204.162   3306.762  13693
some college         29045.443644  25618.4640  153349.533   5514.581    675

Observando la distribución de los clientes en los grupos de edad y de educación decidí usar la **edad** para definir el valor que usare para reemplazar los datos ausentes de los ingresos mensuales. 

Los clientes se distribuyen uniformemente en los grupos de edad y se nota como los ingresos se comportan en aumento a medida que aumenta la edad y luego empieza a bajar al acercarse a la edad de retiro, sin embargo, hay valores atípicos en el maximo y el minimo en todos los grupos por lo cual usare la **mediana**. 

In [46]:
# Imprimiendo las medianas para verificarlas antes de reemplazar
medians = credit_scoring[credit_scoring.total_income.notnull()].groupby("age_group_dec").total_income.median()
medians

age_group_dec
+70      18611.5935
18-30    22957.1850
31-40    24825.1865
41-50    24563.6500
51-60    22056.7710
61-70    19705.8550
Name: total_income, dtype: float64

In [47]:
# Muestra de parte del DataFrame para poder probar mi función:
credit_scoring[credit_scoring['total_income'].isna()].sample(n=10)

children  days_employed  dob_years            education  education_id  \
3948          0            NaN         44    bachelor's degree             0   
17621         0            NaN         41    bachelor's degree             0   
8120          0            NaN         36    bachelor's degree             0   
18401         0            NaN         55    bachelor's degree             0   
4699          0            NaN         33  secondary education             1   
17546         0            NaN         64  secondary education             1   
5124          0            NaN         40  secondary education             1   
5086          0            NaN         42  secondary education             1   
12741         2            NaN         37  secondary education             1   
5690          0            NaN         60    bachelor's degree             0   

           family_status  family_status_id gender    income_type  debt  \
3948           unmarried                 4      F       employee     0   
17621  civil partnership                 1      M       business     0   
8120             married                 0      F       business     0   
18401            married                 0      M       business     0   
4699             married                 0      F  civil servant     0   
17546            married                 0      F        retiree     0   
5124   civil partnership                 1      F       business     0   
5086             married                 0      F       employee     0   
12741  civil partnership                 1      M       employee     0   
5690   civil partnership                 1      F  civil servant     0   

       total_income                                   purpose age_group_dec  
3948            NaN                              to own a car         41-50  
17621           NaN                          wedding ceremony         41-50  
8120            NaN                        housing renovation         31-40  
18401           NaN  transactions with commercial real estate         51-60  
4699            NaN                              car purchase         31-40  
17546           NaN                       going to university         61-70  
5124            NaN                         to have a wedding         31-40  
5086            NaN                  second-hand car purchase         41-50  
12741           NaN                      housing transactions         31-40  
5690            NaN                          having a wedding         51-60

In [48]:
medians = credit_scoring[credit_scoring.total_income.notnull()].groupby("age_group_dec").total_income.median()
def nan_total_income(row):
    age_group = row['age_group_dec']
    total_income = row['total_income']
    if pd.isna(total_income):
        return medians[age_group]
    return total_income

In [49]:
display(credit_scoring.info())
credit_scoring['total_income'] = credit_scoring.apply(nan_total_income,axis=1)
display(credit_scoring)
display(credit_scoring.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      19351 non-null  float64
 11  purpose           21525 non-null  object 
 12  age_group_dec     21525 non-null  object 
dtypes: float64(2), int64(5), object(6)
memory usage: 2.1+ MB


None

children  days_employed  dob_years            education  education_id  \
0             1    8437.673028         42    bachelor's degree             0   
1             1    4024.803754         36  secondary education             1   
2             0    5623.422610         33  secondary education             1   
3             3    4124.747207         32  secondary education             1   
4             0  340266.072047         53  secondary education             1   
...         ...            ...        ...                  ...           ...   
21520         1    4529.316663         43  secondary education             1   
21521         0  343937.404131         67  secondary education             1   
21522         1    2113.346888         38  secondary education             1   
21523         3    3112.481705         38  secondary education             1   
21524         2    1984.507589         40  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
0                married                 0      F    employee     0   
1                married                 0      F    employee     0   
2                married                 0      M    employee     0   
3                married                 0      M    employee     0   
4      civil partnership                 1      F     retiree     0   
...                  ...               ...    ...         ...   ...   
21520  civil partnership                 1      F    business     0   
21521            married                 0      F     retiree     0   
21522  civil partnership                 1      M    employee     1   
21523            married                 0      M    employee     1   
21524            married                 0      F    employee     0   

       total_income                  purpose age_group_dec  
0         40620.102    purchase of the house         41-50  
1         17932.802             car purchase         31-40  
2         23341.752    purchase of the house         31-40  
3         42820.568  supplementary education         31-40  
4         25378.572        to have a wedding         51-60  
...             ...                      ...           ...  
21520     35966.698     housing transactions         41-50  
21521     24959.969        purchase of a car         61-70  
21522     14347.610                 property         31-40  
21523     39054.888        buying my own car         31-40  
21524     13127.587             to buy a car         31-40  

[21525 rows x 13 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      21525 non-null  float64
 11  purpose           21525 non-null  object 
 12  age_group_dec     21525 non-null  object 
dtypes: float64(2), int64(5), object(6)
memory usage: 2.1+ MB


None

In [50]:
# Comprueba si funciona
# 18-30    22957.1850
print(credit_scoring.loc[5740])

# 31-40    24825.1865
print(credit_scoring.loc[4437])

credit_scoring[credit_scoring.total_income.isna()] # Probando que no hay valores ausentes en total_income

children                               0
days_employed                        NaN
dob_years                             21
education            secondary education
education_id                           1
family_status                  unmarried
family_status_id                       4
gender                                 M
income_type                     employee
debt                                   0
total_income                   22957.185
purpose             university education
age_group_dec                      18-30
Name: 5740, dtype: object
children                                  0
days_employed                           NaN
dob_years                                40
education               secondary education
education_id                              1
family_status                     unmarried
family_status_id                          4
gender                                    M
income_type                        employee
debt                                      0
t

Empty DataFrame
Columns: [children, days_employed, dob_years, education, education_id, family_status, family_status_id, gender, income_type, debt, total_income, purpose, age_group_dec]
Index: []

In [51]:
# Comprobar el número de entradas en las columnas
credit_scoring.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      21525 non-null  float64
 11  purpose           21525 non-null  object 
 12  age_group_dec     21525 non-null  object 
dtypes: float64(2), int64(5), object(6)
memory usage: 2.1+ MB


###  Restaurar valores en `days_employed`

para reemplazar los datos de días trabajados agrupare los clientes por el **edad y genero** debido a que estos parametros pueden interferir en los días trabajados de una persona.

Antes de hacer los calculos transformare el 16% de los datos que son mayores a 20.000 días trabajados por cero para despues sustituir el valor con el mismo críterio que para los demás valores ausentes. En total reemplazare un 26% de los datos de days_employed para poder conservar esas filas.

In [52]:
# reemplazo todos los valores mayores a 20.000 dias trabajados por cero
credit_scoring.loc[(credit_scoring["days_employed"]>20000), "days_employed"] = 0 
# Comprobando
credit_scoring[credit_scoring['days_employed']==0]
#Creando un data frame sin nulos ni valores cero para calcular datos estadisticos
credit_scoring_filt = credit_scoring.dropna()
credit_scoring_filt = credit_scoring_filt[credit_scoring_filt['days_employed']>0]
credit_scoring_filt

children  days_employed  dob_years            education  education_id  \
0             1    8437.673028         42    bachelor's degree             0   
1             1    4024.803754         36  secondary education             1   
2             0    5623.422610         33  secondary education             1   
3             3    4124.747207         32  secondary education             1   
5             0     926.185831         27    bachelor's degree             0   
...         ...            ...        ...                  ...           ...   
21519         1    2351.431934         37      graduate degree             4   
21520         1    4529.316663         43  secondary education             1   
21522         1    2113.346888         38  secondary education             1   
21523         3    3112.481705         38  secondary education             1   
21524         2    1984.507589         40  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
0                married                 0      F    employee     0   
1                married                 0      F    employee     0   
2                married                 0      M    employee     0   
3                married                 0      M    employee     0   
5      civil partnership                 1      M    business     0   
...                  ...               ...    ...         ...   ...   
21519           divorced                 3      M    employee     0   
21520  civil partnership                 1      F    business     0   
21522  civil partnership                 1      M    employee     1   
21523            married                 0      M    employee     1   
21524            married                 0      F    employee     0   

       total_income                     purpose age_group_dec  
0         40620.102       purchase of the house         41-50  
1         17932.802                car purchase         31-40  
2         23341.752       purchase of the house         31-40  
3         42820.568     supplementary education         31-40  
5         40922.170       purchase of the house         18-30  
...             ...                         ...           ...  
21519     18551.846  buy commercial real estate         31-40  
21520     35966.698        housing transactions         41-50  
21522     14347.610                    property         31-40  
21523     39054.888           buying my own car         31-40  
21524     13127.587                to buy a car         31-40  

[15906 rows x 13 columns]

In [53]:
# Comparando la media, la mediana, el máximo y el mínimo de los días trabajados según edad:
days_employed_grouped_ag = credit_scoring_filt.groupby(['age_group_dec', 'gender']).agg(
{'days_employed': ['mean', 'median', 'max', 'min', 'count']}
)
days_employed_grouped_ag

days_employed                                          \
                              mean       median           max          min   
age_group_dec gender                                                         
+70           F        3866.172274  1678.969771  10093.858479   730.874426   
              M        4137.066471  2761.484453   7920.082429  1729.632531   
18-30         F        1303.521528  1094.350734   5147.883548    51.496885   
              M        1246.610213   980.806341   5673.867214    67.036625   
31-40         F        2136.344388  1693.069607   9762.839918    24.141633   
              M        2018.572495  1496.333746   8602.090178    24.240695   
41-50         F        2999.429471  2254.431130  13724.223884    47.109840   
              M        2424.808463  1777.966556  11787.798590    30.195337   
51-60         F        3568.865959  2534.240778  16593.472817    58.276481   
              M        2820.656468  1929.913775  15267.541183    65.163190   
61-70         F        4439.457965  3267.564926  18388.949901   100.309421   
              M        2827.548580  1913.690402  14381.545844   114.047745   

                            
                     count  
age_group_dec gender        
+70           F          9  
              M          3  
18-30         F       1952  
              M       1407  
31-40         F       3145  
              M       1988  
41-50         F       3041  
              M       1605  
51-60         F       1551  
              M        821  
61-70         F        248  
              M        136

Para esta variable usare la combinacion del **grupo de datos por edad y el genero** porque son los grupos que tienen datos menos atipicos entre si al comparar entre la máxima y la mínima. Usare la **mediana** por la existencia de datos muy dispersos entre si.   

In [54]:
# Imprimiendo las medianas para verificarlas antes de reemplazar
medians = credit_scoring_filt.groupby(["age_group_dec", 'gender']).days_employed.median()
medians

age_group_dec  gender
+70            F         1678.969771
               M         2761.484453
18-30          F         1094.350734
               M          980.806341
31-40          F         1693.069607
               M         1496.333746
41-50          F         2254.431130
               M         1777.966556
51-60          F         2534.240778
               M         1929.913775
61-70          F         3267.564926
               M         1913.690402
Name: days_employed, dtype: float64

In [55]:
# Muestra de parte del DataFrame para despues poder probar mi función:
credit_scoring[credit_scoring['days_employed'].isna()].sample(n=10)

children  days_employed  dob_years            education  education_id  \
16588         2            NaN         34  secondary education             1   
2656          0            NaN         38  secondary education             1   
21510         2            NaN         28  secondary education             1   
8179          0            NaN         46  secondary education             1   
9284          1            NaN         36  secondary education             1   
12315         0            NaN         40  secondary education             1   
2900          0            NaN         35  secondary education             1   
6431          1            NaN         36    bachelor's degree             0   
3675          0            NaN         37  secondary education             1   
14684         0            NaN         55  secondary education             1   

      family_status  family_status_id gender    income_type  debt  \
16588       married                 0      M       business     0   
2656        married                 0      M       business     0   
21510       married                 0      F       employee     0   
8179      unmarried                 4      F  civil servant     0   
9284       divorced                 3      F       employee     0   
12315       married                 0      F       business     0   
2900        married                 0      M       employee     0   
6431        married                 0      F       employee     0   
3675        married                 0      M       employee     0   
14684       married                 0      F       employee     0   

       total_income                           purpose age_group_dec  
16588    24825.1865                         education         31-40  
2656     24825.1865                           housing         31-40  
21510    22957.1850                      car purchase         18-30  
8179     24563.6500  to get a supplementary education         41-50  
9284     24825.1865                 purchase of a car         31-40  
12315    24825.1865                      to own a car         31-40  
2900     24825.1865                      to buy a car         31-40  
6431     24825.1865          real estate transactions         31-40  
3675     24825.1865              getting an education         31-40  
14684    22056.7710      construction of own property         51-60

In [56]:
# función que usaremos para completar los valores ausentes en days_employed:
       
def replace_nan_days_employed(credit_scoring):
    medians = credit_scoring_filt.groupby(["age_group_dec", 'gender']).days_employed.median()
    
    credit_scoring.loc[credit_scoring["days_employed"].isna() & (credit_scoring["age_group_dec"] == "+70") & (credit_scoring["gender"] == "M") , "days_employed"] = medians.loc["+70", 'M'] # reemplazo todos los nulos que sean hombres mayores de 70 por la mediana de ese grupo
    credit_scoring.loc[credit_scoring["days_employed"].isna() & (credit_scoring["age_group_dec"] == "+70") & (credit_scoring["gender"] == "F") , "days_employed"] = medians.loc["+70", 'F']# reemplazo todos los nulos que sean mujeres mayores de 70 por la mediana de ese grupo
    credit_scoring.loc[credit_scoring["days_employed"].isna() & (credit_scoring["age_group_dec"] == "61-70") & (credit_scoring["gender"] == "M"), "days_employed"] = medians.loc[ "61-70", 'M'] # reemplazo los nulos de hombres de edad 61-70 por la mediana de ese grupo
    credit_scoring.loc[credit_scoring["days_employed"].isna() & (credit_scoring["age_group_dec"] == "61-70") & (credit_scoring["gender"] == "F"), "days_employed"] = medians.loc[ "61-70", 'F'] # reemplazo los nulos de mujeres de edad 61-70 por la mediana de ese grupo
    credit_scoring.loc[credit_scoring["days_employed"].isna() & (credit_scoring["age_group_dec"] == "51-60") & (credit_scoring["gender"] == "M"), "days_employed"] = medians.loc["51-60", 'M'] # Reemplaza los nulos de hombre entre 51-60 por la mediana de ese grupo
    credit_scoring.loc[credit_scoring["days_employed"].isna() & (credit_scoring["age_group_dec"] == "51-60") & (credit_scoring["gender"] == "F"), "days_employed"] = medians.loc["51-60", 'F'] # Reemplaza los nulos de mujeres entre 51-60 por la mediana de ese grupo
    credit_scoring.loc[credit_scoring["days_employed"].isna() & (credit_scoring["age_group_dec"] == "41-50") & (credit_scoring["gender"] == "M"), "days_employed"] = medians.loc["41-50", 'M'] # Reemplaza los nulos de hombres entre 41-50 por la mediana de ese grupo
    credit_scoring.loc[credit_scoring["days_employed"].isna() & (credit_scoring["age_group_dec"] == "41-50") & (credit_scoring["gender"] == "F"), "days_employed"] = medians.loc["41-50", 'F'] # Reemplaza los nulos de mujeres entre 41-50 por la mediana de ese grupo
    credit_scoring.loc[credit_scoring["days_employed"].isna() & (credit_scoring["age_group_dec"] == "31-40")  & (credit_scoring["gender"] == "M"), "days_employed"] = medians.loc["31-40", 'M'] # Reemplaza los nulos de hombre entre 31-40 por la mediana de ese grupo
    credit_scoring.loc[credit_scoring["days_employed"].isna() & (credit_scoring["age_group_dec"] == "31-40")  & (credit_scoring["gender"] == "F"), "days_employed"] = medians.loc["31-40", 'F'] # Reemplaza los nulos de mujeres entre 31-40 por la mediana de ese grupo
    credit_scoring.loc[credit_scoring["days_employed"].isna() & (credit_scoring["age_group_dec"] == "18-30")  & (credit_scoring["gender"] == "M"), "days_employed"] = medians.loc["18-30", 'M'] # Reemplaza los nulos de hombres entre 18-30 por la mediana de ese grupo
    credit_scoring.loc[credit_scoring["days_employed"].isna() & (credit_scoring["age_group_dec"] == "18-30")  & (credit_scoring["gender"] == "F"), "days_employed"] = medians.loc["18-30", 'F'] # Reemplaza los nulos de mujeres entre 18-30 por la mediana de ese grupo
    return credit_scoring

# Aplicando la funcion:
credit_scoring = replace_nan_days_employed(credit_scoring)

# Probando que los datos fueron reemplazados:
credit_scoring

children  days_employed  dob_years            education  education_id  \
0             1    8437.673028         42    bachelor's degree             0   
1             1    4024.803754         36  secondary education             1   
2             0    5623.422610         33  secondary education             1   
3             3    4124.747207         32  secondary education             1   
4             0       0.000000         53  secondary education             1   
...         ...            ...        ...                  ...           ...   
21520         1    4529.316663         43  secondary education             1   
21521         0       0.000000         67  secondary education             1   
21522         1    2113.346888         38  secondary education             1   
21523         3    3112.481705         38  secondary education             1   
21524         2    1984.507589         40  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
0                married                 0      F    employee     0   
1                married                 0      F    employee     0   
2                married                 0      M    employee     0   
3                married                 0      M    employee     0   
4      civil partnership                 1      F     retiree     0   
...                  ...               ...    ...         ...   ...   
21520  civil partnership                 1      F    business     0   
21521            married                 0      F     retiree     0   
21522  civil partnership                 1      M    employee     1   
21523            married                 0      M    employee     1   
21524            married                 0      F    employee     0   

       total_income                  purpose age_group_dec  
0         40620.102    purchase of the house         41-50  
1         17932.802             car purchase         31-40  
2         23341.752    purchase of the house         31-40  
3         42820.568  supplementary education         31-40  
4         25378.572        to have a wedding         51-60  
...             ...                      ...           ...  
21520     35966.698     housing transactions         41-50  
21521     24959.969        purchase of a car         61-70  
21522     14347.610                 property         31-40  
21523     39054.888        buying my own car         31-40  
21524     13127.587             to buy a car         31-40  

[21525 rows x 13 columns]

In [57]:
# Comprobando si la función funciona:

# Mujer  51-60    2534 dias
print(credit_scoring.loc[20625])

# Hombre 18-30   981 dias
print(credit_scoring.loc[12042])

#Mujer 41-50   2254 dias
print(credit_scoring.loc[9847])

credit_scoring[credit_scoring.total_income.isna()] # Probando que no hay valores ausentes en total_income

children                              0
days_employed               2534.240778
dob_years                            56
education           secondary education
education_id                          1
family_status           widow / widower
family_status_id                      2
gender                                F
income_type                     retiree
debt                                  0
total_income                  22056.771
purpose              housing renovation
age_group_dec                     51-60
Name: 20625, dtype: object
children                                           0
days_employed                             980.806341
dob_years                                         26
education                               some college
education_id                                       2
family_status                                married
family_status_id                                   0
gender                                             M
income_type                  

Empty DataFrame
Columns: [children, days_employed, dob_years, education, education_id, family_status, family_status_id, gender, income_type, debt, total_income, purpose, age_group_dec]
Index: []

In [58]:
# función que usaremos para completar los valores cero en days_employed:
       
def replace_cero_days_employed(credit_scoring):
    medians = credit_scoring_filt.groupby(["age_group_dec", 'gender']).days_employed.median()
    
    credit_scoring.loc[(credit_scoring["days_employed"]==0) & (credit_scoring["age_group_dec"] == "+70") & (credit_scoring["gender"] == "M") , "days_employed"] = medians.loc["+70", 'M'] # reemplazo todos los ceros que sean hombres mayores de 70 por la mediana de ese grupo
    credit_scoring.loc[(credit_scoring["days_employed"]==0) & (credit_scoring["age_group_dec"] == "+70") & (credit_scoring["gender"] == "F") , "days_employed"] = medians.loc["+70", 'F']# reemplazo todos los ceros que sean mujeres mayores de 70 por la mediana de ese grupo
    credit_scoring.loc[(credit_scoring["days_employed"]==0) & (credit_scoring["age_group_dec"] == "61-70") & (credit_scoring["gender"] == "M"), "days_employed"] = medians.loc[ "61-70", 'M'] # reemplazo los ceros de hombres de edad 61-70 por la mediana de ese grupo
    credit_scoring.loc[(credit_scoring["days_employed"]==0) & (credit_scoring["age_group_dec"] == "61-70") & (credit_scoring["gender"] == "F"), "days_employed"] = medians.loc[ "61-70", 'F'] # reemplazo los ceros de mujeres de edad 61-70 por la mediana de ese grupo
    credit_scoring.loc[(credit_scoring["days_employed"]==0) & (credit_scoring["age_group_dec"] == "51-60") & (credit_scoring["gender"] == "M"), "days_employed"] = medians.loc["51-60", 'M'] # Reemplaza los ceros de hombre entre 51-60 por la mediana de ese grupo
    credit_scoring.loc[(credit_scoring["days_employed"]==0) & (credit_scoring["age_group_dec"] == "51-60") & (credit_scoring["gender"] == "F"), "days_employed"] = medians.loc["51-60", 'F'] # Reemplaza los ceros de mujeres entre 51-60 por la mediana de ese grupo
    credit_scoring.loc[(credit_scoring["days_employed"]==0) & (credit_scoring["age_group_dec"] == "41-50") & (credit_scoring["gender"] == "M"), "days_employed"] = medians.loc["41-50", 'M'] # Reemplaza los ceros de hombres entre 41-50 por la mediana de ese grupo
    credit_scoring.loc[(credit_scoring["days_employed"]==0) & (credit_scoring["age_group_dec"] == "41-50") & (credit_scoring["gender"] == "F"), "days_employed"] = medians.loc["41-50", 'F'] # Reemplaza los ceros de mujeres entre 41-50 por la mediana de ese grupo
    credit_scoring.loc[(credit_scoring["days_employed"]==0) & (credit_scoring["age_group_dec"] == "31-40")  & (credit_scoring["gender"] == "M"), "days_employed"] = medians.loc["31-40", 'M'] # Reemplaza los ceros de hombre entre 31-40 por la mediana de ese grupo
    credit_scoring.loc[(credit_scoring["days_employed"]==0) & (credit_scoring["age_group_dec"] == "31-40")  & (credit_scoring["gender"] == "F"), "days_employed"] = medians.loc["31-40", 'F'] # Reemplaza los ceros de mujeres entre 31-40 por la mediana de ese grupo
    credit_scoring.loc[(credit_scoring["days_employed"]==0) & (credit_scoring["age_group_dec"] == "18-30")  & (credit_scoring["gender"] == "M"), "days_employed"] = medians.loc["18-30", 'M'] # Reemplaza los ceros de hombres entre 18-30 por la mediana de ese grupo
    credit_scoring.loc[(credit_scoring["days_employed"]==0) & (credit_scoring["age_group_dec"] == "18-30")  & (credit_scoring["gender"] == "F"), "days_employed"] = medians.loc["18-30", 'F'] # Reemplaza los ceros de mujeres entre 18-30 por la mediana de ese grupo
    return credit_scoring

# Aplicando la funcion:
credit_scoring = replace_cero_days_employed(credit_scoring)

# Probando que los datos fueron reemplazados:
credit_scoring[credit_scoring['days_employed']==0]

Empty DataFrame
Columns: [children, days_employed, dob_years, education, education_id, family_status, family_status_id, gender, income_type, debt, total_income, purpose, age_group_dec]
Index: []

In [59]:
# Verificando los cambios en el DataFrame
credit_scoring.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     21525 non-null  float64
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      21525 non-null  float64
 11  purpose           21525 non-null  object 
 12  age_group_dec     21525 non-null  object 
dtypes: float64(2), int64(5), object(6)
memory usage: 2.1+ MB


In [60]:
# Cambiando los datos de dias trabajados a valores enteros ya que no es posible tener menos de un dia trabadado:
credit_scoring['days_employed']=credit_scoring['days_employed'].astype('int')

# Comprobando que ya no hay valores ausentes en el DataFrame y que los datos en days_employed son numeros enteros:
credit_scoring.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     21525 non-null  int32  
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      21525 non-null  float64
 11  purpose           21525 non-null  object 
 12  age_group_dec     21525 non-null  object 
dtypes: float64(1), int32(1), int64(5), object(6)
memory usage: 2.1+ MB


## Clasificación de datos

### Clasificando datos no númericos:

In [61]:
# Veamos los diferentes proposito por los que se pide un prestamo para agrupar los que sean similares:
credit_scoring['purpose'].value_counts()


wedding ceremony                            797
having a wedding                            777
to have a wedding                           774
real estate transactions                    676
buy commercial real estate                  664
buying property for renting out             653
housing transactions                        653
transactions with commercial real estate    651
purchase of the house                       647
housing                                     647
purchase of the house for my family         641
construction of own property                635
property                                    634
transactions with my real estate            630
building a real estate                      626
buy real estate                             624
building a property                         620
purchase of my own house                    620
housing renovation                          612
buy residential real estate                 607
buying my own car                       

Dentro de los propositos para solicitar un prestamo hay varios que son para el mismo proposito pero descritos de varias formas como los de las bodas, comprar un auto, etc.

Voy a agruparlos en categorias de la siguiente manera:
* Todos los que tengan la palabra **wedding** en una categoría con el mismo nombre.
* Todos los que tengan la palabra **car** en una categoría con el mismo nombre.
* Todos los que contengan las palabras **education, educated and university** en la categoría 'education'.
* Todos los que contengan las palabras **estate** en la categoría 'real_estate'
* Todos los que tengan las palabras **housing, house, construction, property** en la categoría 'own_property'

In [62]:
# Escribamos una función para clasificar los datos en función de proposito para usar el prestamo:
def purpose_cat(x):
        
    if 'wedding' in x:
        return 'wedding'
    if 'car' in x:
        return 'car'
    if 'education' in x or 'educated' in x or 'university' in x:
        return 'education'
    if 'estate' in x:
        return 'real_estate'
    else:
        return 'own_property'

In [63]:
# Creando una columna para las nuevas categorias:
credit_scoring['purpose_cat'] = credit_scoring['purpose'].apply(purpose_cat)

# Traigo una muestra aleatoria de los datos para verificar si los cambios se aplicaron correctamente:
credit_scoring.sample(n=20)

children  days_employed  dob_years            education  education_id  \
9912          1            781         24    bachelor's degree             0   
2567          0            408         40  secondary education             1   
6540          0           3267         62    bachelor's degree             0   
4908          1           4980         47    bachelor's degree             0   
13671         0           2448         42  secondary education             1   
7683          0            173         45  secondary education             1   
13626         1           4485         40  secondary education             1   
13663         1           1489         42  secondary education             1   
6805          0           2534         52  secondary education             1   
18632         1           5907         38  secondary education             1   
13132         0            223         25    bachelor's degree             0   
2051          0            959         29  secondary education             1   
14370         0           3267         64    bachelor's degree             0   
16710         0           3782         39  secondary education             1   
12816         0           2302         30  secondary education             1   
17435         0           5807         54  secondary education             1   
8827          1            516         45  secondary education             1   
3017          2           1595         26  secondary education             1   
16353         1           1491         26  secondary education             1   
19412         0            150         55    bachelor's degree             0   

           family_status  family_status_id gender    income_type  debt  \
9912           unmarried                 4      F       employee     0   
2567   civil partnership                 1      F       employee     0   
6540             married                 0      F        retiree     0   
4908   civil partnership                 1      M  civil servant     0   
13671           divorced                 3      F       employee     0   
7683           unmarried                 4      M       employee     1   
13626            married                 0      M       employee     0   
13663            married                 0      M       business     0   
6805             married                 0      F        retiree     0   
18632    widow / widower                 2      M       employee     0   
13132  civil partnership                 1      M       employee     0   
2051             married                 0      M       employee     0   
14370            married                 0      F        retiree     0   
16710  civil partnership                 1      M       business     0   
12816            married                 0      F  civil servant     0   
17435            married                 0      M       employee     0   
8827             married                 0      F       business     0   
3017             married                 0      F       employee     0   
16353            married                 0      F       employee     0   
19412            married                 0      F       business     0   

       total_income                              purpose age_group_dec  \
9912      14259.963             purchase of my own house         18-30   
2567      16337.295                     wedding ceremony         31-40   
6540      90945.814     to get a supplementary education         61-70   
4908      43968.243                     having a wedding         41-50   
13671     42562.686  purchase of the house for my family         41-50   
7683      45760.338                    profile education         41-50   
13626     18449.845             getting higher education         31-40   
13663     24078.377                         to own a car         41-50   
6805      25807.496                  building a property         51-60   
18632      8702.576            

In [64]:
# Verificando la cabtidad de datos en las nuevas categorias:
credit_scoring['purpose_cat'].value_counts()

own_property    6362
real_estate     4478
car             4315
education       4022
wedding         2348
Name: purpose_cat, dtype: int64

### Clasificando datos númericos:

In [65]:
# Revisando 'total_income'
credit_scoring['total_income'].value_counts()

24825.1865    573
24563.6500    533
22056.7710    490
22957.1850    357
19705.8550    216
             ... 
23686.8350      1
9606.2940       1
28156.7620      1
24931.1950      1
13127.5870      1
Name: total_income, Length: 19351, dtype: int64

In [66]:



# Obtener estadísticas resumidas para la columna
credit_scoring['total_income'].describe()

count     21525.000000
mean      26435.589154
std       15665.327727
min        3306.762000
25%       17247.708000
50%       23225.474000
75%       31286.979000
max      362496.645000
Name: total_income, dtype: float64

Agrupare los ingresos mensuales por rangos de la siguiente forma:
* Menos o igual a 5.000 '-5k'
* De 5.001 a menos de 10.000 '5-10k'
* Desde 10.001 y menos de 20.000 '10-20k'
* Desde 20.001 y menos de 30.000 '20-30k'
* Desde 30.001 y menos de 40.000 '30-40k'
* Mas de 40.000 '+40k'

Usare estas categorias porque según la distribución estadística gran parte de los datos están entre el rango de los 10.000 y 30.000.

In [67]:
# Crear una función para clasificar el total_income por rangos de ingresos mensuales:

def total_income_cat(x):
    ingresos=x['total_income']
    
    if ingresos <= 5000: 
        return '-5k'  
    if 5000 < ingresos <= 10000:
        return '5-10k'
    if 10000 < ingresos <= 20000:
        return '10-20k'
    if 20000 < ingresos <= 30000:
        return '20-30k'
    if 30000 < ingresos <= 40000:
        return '30-40k' 
    return '+40k'  

In [68]:
# Crear una columna con categorías
credit_scoring['total_income_cat'] = credit_scoring.apply(total_income_cat, axis=1)
credit_scoring

children  days_employed  dob_years            education  education_id  \
0             1           8437         42    bachelor's degree             0   
1             1           4024         36  secondary education             1   
2             0           5623         33  secondary education             1   
3             3           4124         32  secondary education             1   
4             0           2534         53  secondary education             1   
...         ...            ...        ...                  ...           ...   
21520         1           4529         43  secondary education             1   
21521         0           3267         67  secondary education             1   
21522         1           2113         38  secondary education             1   
21523         3           3112         38  secondary education             1   
21524         2           1984         40  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
0                married                 0      F    employee     0   
1                married                 0      F    employee     0   
2                married                 0      M    employee     0   
3                married                 0      M    employee     0   
4      civil partnership                 1      F     retiree     0   
...                  ...               ...    ...         ...   ...   
21520  civil partnership                 1      F    business     0   
21521            married                 0      F     retiree     0   
21522  civil partnership                 1      M    employee     1   
21523            married                 0      M    employee     1   
21524            married                 0      F    employee     0   

       total_income                  purpose age_group_dec   purpose_cat  \
0         40620.102    purchase of the house         41-50  own_property   
1         17932.802             car purchase         31-40           car   
2         23341.752    purchase of the house         31-40  own_property   
3         42820.568  supplementary education         31-40     education   
4         25378.572        to have a wedding         51-60       wedding   
...             ...                      ...           ...           ...   
21520     35966.698     housing transactions         41-50  own_property   
21521     24959.969        purchase of a car         61-70           car   
21522     14347.610                 property         31-40  own_property   
21523     39054.888        buying my own car         31-40           car   
21524     13127.587             to buy a car         31-40           car   

      total_income_cat  
0                 +40k  
1               10-20k  
2               20-30k  
3                 +40k  
4               20-30k  
...                ...  
21520           30-40k  
21521           20-30k  
21522           10-20k  
21523           30-40k  
21524           10-20k  

[21525 rows x 15 columns]

In [69]:
# Contar los valores de cada categoría para ver la distribución
credit_scoring['total_income_cat'].value_counts()

20-30k    8014
10-20k    6666
30-40k    3107
+40k      2812
5-10k      900
-5k         26
Name: total_income_cat, dtype: int64

In [70]:
# Revisando la columna de días trabajados:
credit_scoring['days_employed'].describe()

count    21525.000000
mean      2356.519257
std       2008.325733
min         24.000000
25%        999.000000
50%       1929.000000
75%       3113.000000
max      18388.000000
Name: days_employed, dtype: float64

Agrupare los días trabajados por rangos de la siguiente forma:

* Menos o igual a 180 '-6 meses'
* De 181 días a 365 dias '6-12 meses'
* De 366 a 730 '1-2 años'
* De 731 días a 1.097 '2-3 años'
* De 1.098 a 1.460 '3-4 años'
* De 1.461 a 1.825 '4-5 años'
* De 1.826 a 2.190 '5-6 años'
* De 2.191 a 2.555 '6-7 años'
* De 2.556 a 2.920 '7-8 años'
* De 2.921 a 3.281 dias '8-9 años'
* Mas de 3.281 dias '+9 años'

Categorice los datos por meses y años trabajados ya que así es más fácil de visualizar la antigüedad laboral.

In [71]:
# función para clasificar el days_employed por años y meses de antigüedad laboral:

def days_employed_cat(x):
    dias=x['days_employed']
    
    if dias <= 180: 
        return '-6 m'  
    if 181 < dias <= 365:
        return '6-12m'
    if 365 < dias <= 730:
        return '1-2a'
    if 730 < dias <= 1097:
        return '2-3a'
    if 1097 < dias <= 1460:
        return '3-4a'
    if 1460 < dias <= 1825:
        return '4-5a'
    if 1825 < dias <= 2190:
        return '5-6a'
    if 2190 < dias <= 2555:
        return '6-7a'
    if 2555 < dias <= 2920:
        return '7-8a'
    if 2920 < dias <= 3281:
        return '8-9a'
    return '+9a'  

In [72]:
# Crear una columna con categorías antigüedad laboral:
credit_scoring['days_employed_cat'] = credit_scoring.apply(days_employed_cat, axis=1)
credit_scoring

children  days_employed  dob_years            education  education_id  \
0             1           8437         42    bachelor's degree             0   
1             1           4024         36  secondary education             1   
2             0           5623         33  secondary education             1   
3             3           4124         32  secondary education             1   
4             0           2534         53  secondary education             1   
...         ...            ...        ...                  ...           ...   
21520         1           4529         43  secondary education             1   
21521         0           3267         67  secondary education             1   
21522         1           2113         38  secondary education             1   
21523         3           3112         38  secondary education             1   
21524         2           1984         40  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
0                married                 0      F    employee     0   
1                married                 0      F    employee     0   
2                married                 0      M    employee     0   
3                married                 0      M    employee     0   
4      civil partnership                 1      F     retiree     0   
...                  ...               ...    ...         ...   ...   
21520  civil partnership                 1      F    business     0   
21521            married                 0      F     retiree     0   
21522  civil partnership                 1      M    employee     1   
21523            married                 0      M    employee     1   
21524            married                 0      F    employee     0   

       total_income                  purpose age_group_dec   purpose_cat  \
0         40620.102    purchase of the house         41-50  own_property   
1         17932.802             car purchase         31-40           car   
2         23341.752    purchase of the house         31-40  own_property   
3         42820.568  supplementary education         31-40     education   
4         25378.572        to have a wedding         51-60       wedding   
...             ...                      ...           ...           ...   
21520     35966.698     housing transactions         41-50  own_property   
21521     24959.969        purchase of a car         61-70           car   
21522     14347.610                 property         31-40  own_property   
21523     39054.888        buying my own car         31-40           car   
21524     13127.587             to buy a car         31-40           car   

      total_income_cat days_employed_cat  
0                 +40k               +9a  
1               10-20k               +9a  
2               20-30k               +9a  
3                 +40k               +9a  
4               20-30k              6-7a  
...                ...               ...  
21520           30-40k               +9a  
21521           20-30k              8-9a  
21522           10-20k              5-6a  
21523           30-40k              8-9a  
21524           10-20k              5-6a  

[21525 rows x 16 columns]

In [73]:
# Contar los valores de cada categoría para ver la distribución
credit_scoring['days_employed_cat'].value_counts()

+9a      3729
6-7a     3273
4-5a     2257
2-3a     2251
8-9a     2062
1-2a     2019
5-6a     1724
3-4a     1552
6-12m    1222
7-8a      828
-6 m      608
Name: days_employed_cat, dtype: int64

## Comprobación de las hipótesis


Antes de empezar a analizar los datos extraere una tabla con los datos relevantes para analizar, asi podre visualizar mejor los datos que necesito.

In [74]:
#Eliminando las columnas con datos que ya agrupe en nuevas columnas:
data_final = credit_scoring.drop(columns=['days_employed', 'dob_years', 'education_id', 'family_status_id', 'total_income', 'purpose'])
# Verificando mi nuevo DataFrame
data_final

children            education      family_status gender income_type  \
0             1    bachelor's degree            married      F    employee   
1             1  secondary education            married      F    employee   
2             0  secondary education            married      M    employee   
3             3  secondary education            married      M    employee   
4             0  secondary education  civil partnership      F     retiree   
...         ...                  ...                ...    ...         ...   
21520         1  secondary education  civil partnership      F    business   
21521         0  secondary education            married      F     retiree   
21522         1  secondary education  civil partnership      M    employee   
21523         3  secondary education            married      M    employee   
21524         2  secondary education            married      F    employee   

       debt age_group_dec   purpose_cat total_income_cat days_employed_cat  
0         0         41-50  own_property             +40k               +9a  
1         0         31-40           car           10-20k               +9a  
2         0         31-40  own_property           20-30k               +9a  
3         0         31-40     education             +40k               +9a  
4         0         51-60       wedding           20-30k              6-7a  
...     ...           ...           ...              ...               ...  
21520     0         41-50  own_property           30-40k               +9a  
21521     0         61-70           car           20-30k              8-9a  
21522     1         31-40  own_property           10-20k              5-6a  
21523     1         31-40           car           30-40k              8-9a  
21524     0         31-40           car           10-20k              5-6a  

[21525 rows x 10 columns]

Para responder estas preguntas creare dos tablas para separar los clientes que han incumplido alguna vez con un préstamos y los que no lo han hecho, de la siguiente forma:

* Tabla **'data_no_cumpl'** con todos los clientes que han incumplido alguna vez y renombrare la columna **'debt'** como **'no_cumple'**.
* Tabla **'data_cumpl'** con todos los clientes que NO han incumplido alguna vez y renombrare la columna **'debt'** como **'cumple'**.

In [75]:
# Tabla de clientes que han incumplido alguna vez un préstamo:
data_no_cumpl = data_final[data_final['debt']==1]
# Cambiando nombre de columna 'debt' a 'no_cumple':
data_no_cumpl = data_no_cumpl.rename(columns={'debt':'no_cumple'})
data_no_cumpl

children            education      family_status gender income_type  \
14            0    bachelor's degree  civil partnership      F    business   
32            0  secondary education  civil partnership      F    employee   
38            0    bachelor's degree          unmarried      M    employee   
55            0  secondary education  civil partnership      F     retiree   
75            1  secondary education            married      M    employee   
...         ...                  ...                ...    ...         ...   
21494         0  secondary education  civil partnership      M    business   
21511         0    bachelor's degree  civil partnership      F    employee   
21515         1  secondary education            married      F    employee   
21522         1  secondary education  civil partnership      M    employee   
21523         3  secondary education            married      M    employee   

       no_cumple age_group_dec   purpose_cat total_income_cat  \
14             1         51-60   real_estate           20-30k   
32             1         31-40       wedding           20-30k   
38             1         18-30     education           30-40k   
55             1         51-60       wedding           20-30k   
75             1         31-40   real_estate           10-20k   
...          ...           ...           ...              ...   
21494          1         31-40     education           20-30k   
21511          1         18-30  own_property           20-30k   
21515          1         18-30     education           10-20k   
21522          1         31-40  own_property           10-20k   
21523          1         31-40           car           30-40k   

      days_employed_cat  
14                 5-6a  
32                  +9a  
38                 1-2a  
55                 6-7a  
75                 8-9a  
...                 ...  
21494              2-3a  
21511              1-2a  
21515              1-2a  
21522              5-6a  
21523              8-9a  

[1741 rows x 10 columns]

In [76]:
# Tabla de clientes que NO han incumplido alguna vez un préstamo:
data_cumpl = data_final[data_final['debt']==0]
# Cambiando nombre de columna 'debt' a 'cumple':
data_cumpl = data_cumpl.rename(columns={'debt':'cumple'})
data_cumpl

children            education      family_status gender income_type  \
0             1    bachelor's degree            married      F    employee   
1             1  secondary education            married      F    employee   
2             0  secondary education            married      M    employee   
3             3  secondary education            married      M    employee   
4             0  secondary education  civil partnership      F     retiree   
...         ...                  ...                ...    ...         ...   
21518         0  secondary education            married      F     retiree   
21519         1      graduate degree           divorced      M    employee   
21520         1  secondary education  civil partnership      F    business   
21521         0  secondary education            married      F     retiree   
21524         2  secondary education            married      F    employee   

       cumple age_group_dec   purpose_cat total_income_cat days_employed_cat  
0           0         41-50  own_property             +40k               +9a  
1           0         31-40           car           10-20k               +9a  
2           0         31-40  own_property           20-30k               +9a  
3           0         31-40     education             +40k               +9a  
4           0         51-60       wedding           20-30k              6-7a  
...       ...           ...           ...              ...               ...  
21518       0         51-60           car           20-30k              6-7a  
21519       0         31-40   real_estate           10-20k              6-7a  
21520       0         41-50  own_property           30-40k               +9a  
21521       0         61-70           car           20-30k              8-9a  
21524       0         31-40           car           10-20k              5-6a  

[19784 rows x 10 columns]

**¿Existe una correlación entre tener hijos y pagar a tiempo?**

Creare una tabla dinamica para cada caso que agrupe por la cantídad de hijos para calcular la proporción de cumplimiento e incumplimiento según el número de hijos.

In [77]:
# Tabla agrupada de incumplimiento de un préstamo según la cantídad de hijos:
data_child_no_cumpl = data_no_cumpl.pivot_table(
    index='children',
    values= 'no_cumple',
    aggfunc= 'sum'
)
data_child_no_cumpl

no_cumple
children           
0              1063
1               445
2               202
3                27
4                 4

In [78]:
# Tabla agrupada de No incumplimiento de un préstamo según la cantídad de hijos:
data_child_cumpl = data_cumpl.pivot_table(
    index='children',
    values= 'cumple',
    aggfunc= 'count'
)
data_child_cumpl

cumple
children        
0          13086
1           4420
2           1929
3            303
4             37
5              9

In [79]:
# Tabla agrupada de cumplimiento e incumplimiento según el número de hijos:
data_children = data_child_cumpl.merge(right=data_child_no_cumpl, on='children', how='inner')
print(f'Las personas sin hijos que incumplieron un prestamo representan un {1063/(1063+27+445+194+12)*100:.2f}% del incumplimiento total.')
data_children['porc_incump'] = (data_children['no_cumple']*100) / (data_children['cumple']+data_children['no_cumple'])
data_children.sort_values(by='porc_incump')

Las personas sin hijos que incumplieron un prestamo representan un 61.06% del incumplimiento total.


cumple  no_cumple  porc_incump
children                                
0          13086       1063     7.512898
3            303         27     8.181818
1           4420        445     9.146968
2           1929        202     9.479118
4             37          4     9.756098

**Conclusión**

Según la información obtenida solo teniendo en cuenta la cantídad de hijos y el porcentaje de incumplimiento del pago de un prestamo podemos observar que este aumenta levemente en función al número de hijos.
Al observar la cantídad de datos, aunque el porcentaje de incumplimiento es menor en las personas que no tienen hijos el peso del incumplimiento de este grupo es mucho mayor ya que representan un 61% del incumplimiento total.

<div class="alert alert-block alert-success">
<b>Comentario de Reviewer</b> <a class="tocSkip"></a>

Buena conclusión. Hay que corregir el valor de 20 hijos, pero te adelanto que no cambia las conclusiones.
</div>

<div class="alert alert-block alert-info">
<b>Respuesta estudiante.</b> <a class="tocSkip"></a>
Jajaja que bueno! Ya lo cambie y justo estaba pensando en las conclusiones :)
</div>

**¿Existe una correlación entre la situación familiar y el pago a tiempo?**

Creare una tabla dinamica que agrupe por estado civil para calcular la proporción de cumplimiento e incumplimiento según el mismo.

In [80]:
# Tabla agrupada de incumplimiento de un préstamo según estado civil:
data_family_no_cumpl = data_no_cumpl.pivot_table(
    index='family_status',
    values= 'no_cumple',
    aggfunc= 'sum'
)
data_family_no_cumpl

no_cumple
family_status               
civil partnership        388
divorced                  85
married                  931
unmarried                274
widow / widower           63

In [81]:
# Tabla agrupada de No incumplimiento de un préstamo según estado civil:
data_family_cumpl = data_cumpl.pivot_table(
    index='family_status',
    values= 'cumple',
    aggfunc= 'count'
)
data_family_cumpl

cumple
family_status            
civil partnership    3789
divorced             1110
married             11449
unmarried            2539
widow / widower       897

In [82]:
# Tabla agrupada de cumplimiento e incumplimiento según el estado civil:
data_family = data_family_cumpl.merge(right=data_family_no_cumpl, on='family_status', how='inner')
print(f'Las personas casadas representan un {931/(63+85+931+388+274)*100:.2f}% del incumplimiento total.')
data_family['porc_incump'] = (data_family['no_cumple']*100) / (data_family['cumple']+data_family['no_cumple'])
data_family.sort_values(by='porc_incump')

Las personas casadas representan un 53.48% del incumplimiento total.


cumple  no_cumple  porc_incump
family_status                                    
widow / widower       897         63     6.562500
divorced             1110         85     7.112971
married             11449        931     7.520194
civil partnership    3789        388     9.288963
unmarried            2539        274     9.740491

**Conclusión**

Según el porcentaje de cumplimiento las viudas o viudos tienden a ser más cumplidos con el pago de los prestamos, seguidos por los o las divorciadas, mientras que los solteros son los que tienen una proporción mayor de incumplimiento y muy de cerca estan las personas en union civil.
Aunque al observar los datos por cantidad en el total de datos se puede observar que las personas casadas aunque tienen una porcentaje de incumplimiento bajo, representan un 53% del total de clientes que incumplieron un prestamo.

<div class="alert alert-block alert-success">
<b>Comentario de Reviewer</b> <a class="tocSkip"></a>

Excelente!
</div>

**¿Existe una correlación entre el nivel de ingresos y el pago a tiempo?**

Creare una tabla dinamica para cada caso que agrupe por nivel de ingresos para calcular la proporción de cumplimiento e incumplimiento según el mismo.

In [83]:
# Tabla agrupada de incumplimiento de un préstamo según nivel de ingresos:
data_income_no_cumpl = data_no_cumpl.pivot_table(
    index='total_income_cat',
    values= 'no_cumple',
    aggfunc= 'sum'
)
data_income_no_cumpl

no_cumple
total_income_cat           
+40k                    194
-5k                       2
10-20k                  562
20-30k                  685
30-40k                  242
5-10k                    56

In [84]:
# Tabla agrupada de No incumplimiento de un préstamo según nivel de ingresos:
data_income_cumpl = data_cumpl.pivot_table(
    index='total_income_cat',
    values= 'cumple',
    aggfunc= 'count'
)
data_income_cumpl

cumple
total_income_cat        
+40k                2618
-5k                   24
10-20k              6104
20-30k              7329
30-40k              2865
5-10k                844

In [85]:
# Tabla agrupada de cumplimiento e incumplimiento según los ingresos:
data_income = data_income_cumpl.merge(right=data_income_no_cumpl, on='total_income_cat', how='inner')
print(f'Las personas con ingresos entre 10.000 a 30.000 representan un {(685+562)/(194+564+685+242+56)*100:.2f}% del incumplimiento total.')
data_income['porc_incump'] = (data_income['no_cumple']*100) / (data_income['cumple']+data_income['no_cumple'])
data_income.sort_values(by='porc_incump')

Las personas con ingresos entre 10.000 a 30.000 representan un 71.63% del incumplimiento total.


cumple  no_cumple  porc_incump
total_income_cat                                
5-10k                844         56     6.222222
+40k                2618        194     6.899004
-5k                   24          2     7.692308
30-40k              2865        242     7.788864
10-20k              6104        562     8.430843
20-30k              7329        685     8.547542

**Conclusión**

Las personas con mejor cumplimiento son las que tienen ingresos entre 5.000 y 10.000 y las que ganan mas de 40.000, seguidas de los que tienen ingresos menores a 5.000. 
La mayor proporción de incumplimiento esta entre las personas con ingresos entre 10.000 y 30.000 quienes representan casi el 72% del incumplimiento total. Este grupo muestra un comportamiento entre los clientes donde a mayor ingreso mayor incumplimiento. 

**¿Cómo afecta el propósito del crédito a la tasa de incumplimiento?**

Creare una tabla dinamica para cada caso que agrupe por la razón del préstamo para calcular la proporción de cumplimiento e incumplimiento según cada caso.

In [86]:
# Tabla agrupada de incumplimiento de un préstamo según el propósito:
data_purpose_no_cumpl = data_no_cumpl.pivot_table(
    index='purpose_cat',
    values= 'no_cumple',
    aggfunc= 'sum'
)
data_purpose_no_cumpl

no_cumple
purpose_cat            
car                 403
education           370
own_property        446
real_estate         336
wedding             186

In [87]:
# Tabla agrupada de No incumplimiento de un préstamo según el propósito:
data_purpose_cumpl = data_cumpl.pivot_table(
    index='purpose_cat',
    values= 'cumple',
    aggfunc= 'count'
)
data_purpose_cumpl

cumple
purpose_cat         
car             3912
education       3652
own_property    5916
real_estate     4142
wedding         2162

In [88]:
# Tabla agrupada de cumplimiento e incumplimiento según el propósito:
data_purpose = data_purpose_cumpl.merge(right=data_purpose_no_cumpl, on='purpose_cat', how='inner')
print(f'Las personas que usaron el prestamos para comprar una propiedad de uso personal representan el {(446)/(446+336+186+370+403)*100:.2f}% del incumplimiento total.')
print(f'Las personas  que usaron el prestamos para comprar un auto representan el {(403)/(446+336+186+370+403)*100:.2f}% del incumplimiento total.')
data_purpose['porc_incump'] = (data_purpose['no_cumple']*100) / (data_purpose['cumple']+data_purpose['no_cumple'])
data_purpose.sort_values(by='porc_incump')

Las personas que usaron el prestamos para comprar una propiedad de uso personal representan el 25.62% del incumplimiento total.
Las personas  que usaron el prestamos para comprar un auto representan el 23.15% del incumplimiento total.


cumple  no_cumple  porc_incump
purpose_cat                                 
own_property    5916        446     7.010374
real_estate     4142        336     7.503350
wedding         2162        186     7.921635
education       3652        370     9.199403
car             3912        403     9.339513

**Conclusión**

Las personas con mejor cumplimiento de prestamos son las que lo solicitaron para comprar su casa, arregrarla o comprar una propiedad para uso personal, seguido de cerca por quienes lo usaron para comprar propiedades como inversión.

El mayor incumplimiento esta entre quienes usaron el prestamo para comprar un carro, seguido por quienes lo usaron para educación.

Aunque Las personas que usaron el prestamos para comprar una propiedad de uso personal tienen un porcentaje de incumplimiento mucho menor representan el 25.62% del incumplimiento total. Mientras que el grupo con mayor porcentaje de incumplimiento que usaron el prestamos para comprar un auto representan el 23.15% del incumplimiento total.

# Conclusión general 

1. El conjunto de datos venía con varios problemas en los datos como valores negativos en los ingresos mensuales y número de hijos; días trabajados que sumaban mas de 100 años; 10% de datos ausentes algunos clientes con edad cero y las razones para solicitar el prestamo estaban divididas en varías formas de decir lo mismo para una boda, comprar un auto o una propiedad. Tambien agrupe los dias trabajados en años y meses para facilitar la visualización. En general los cambios que realice fueron:

    * Reemplace un 10% de datos de **valores ausentes** en los **ingresos mensules y la antigüedad laboral**. 
    * Reemplace 16% de datos de **antigüedad laboral** que debian ser un error porque eran mayores a 55 años trabajados e incluso miles de años. Use el mismo criterío que con los valores ausentes.
    * Cambie de negativo a positivo la **cantidad de hijos** de 0.22% de datos.
    * Cambie de negativo a positivo 74% de los datos de **antigüedad laboral**.
    * Reemplace el 0,43% de datos de la **edad** porque tenian valor de cero.


2. Se puede observar que el porcentaje de incumplimiento de pago de un prestamo aumenta levemente en función al número de hijos. **Pero en la totalidad de los datos las personas que no tienen hijos representan un 61% del incumplimiento total.**

3. Las viudas o viudos tienden a ser más cumplidos con el pago de los prestamos, seguidos por los o las divorciadas, mientras que los y las solteras son los que tienen una proporción mayor de incumplimiento y muy de cerca estan las personas en union civil. **Aunque al observar los datos en su totalidad las personas casadas que son un grupo con porcentaje de incumplimiento bajo, representan un 53% del total de clientes que incumplieron un prestamo.**

4. Las personas con mejor cumplimiento son las que tienen ingresos entre 5.000 y 10.000 y las que ganan mas de 40.000, seguidas de los que tienen ingresos menores a 5.000. **La mayor proporción de incumplimiento esta entre las personas con ingresos entre 10.000 y 30.000 quienes representan casi el 72% del incumplimiento total. Este grupo muestra un comportamiento entre los clientes donde a mayor ingreso mayor incumplimiento.**

5. Las personas con mejor cumplimiento de prestamos son las que lo solicitaron para comprar su casa, arregrarla o comprar una propiedad para uso personal, seguido de cerca por quienes lo usaron para comprar propiedades como inversión. El mayor incumplimiento esta entre quienes usaron el prestamo para comprar un carro, seguido por quienes lo usaron para educación. **Aunque Las personas que usaron el prestamos para comprar una propiedad de uso personal tienen un porcentaje de incumplimiento mucho menor representan el 25.62% del incumplimiento total. Mientras que el grupo con mayor porcentaje de incumplimiento que usaron el prestamos para comprar un auto representan el 23.15% del incumplimiento total.**

